markdown: redcarpet
highlighter: pygments
permalink: /:title

url:
baseurl: /blog
category_list: [life, algorithm, web]

redcarpet:
  extensions: [strikethrough, tables]

sass:
  sass_dir: public/css
  style: :compressed
