markdown: redcarpet
highlighter: pygments
permalink: /:title

url:
baseurl: /blog

redcarpet:
  extensions: ["fenced_code_blocks", "autolink", "tables", "strikethrough"]

sass:
  sass_dir: public/css
  style: :compressed
